# Programming Assignment 4 (Problem sheet 6)
Héctor Andrade Loarca

We want to implement the CG method for the solution of the linear system $Ax=b$ for a given matrix $A\in S^m$ pos. def. and $b\in \mathbb{R}^n$

Lets define a function `CG` which implements the Conjugate Gradient Method whit inputs, the matrix $A$, the vector $b$, the error $\epsilon$ and maximum number of iterations `maxit`; and as output the solution $x$, the number of required iterations `it` and the vector of residuals, i.e.

`res`=$(||b-Ax^0||,...,||b-Ax^{it}||)$

In [22]:
function CG(A,b,ϵ,maxit)
    #Lets begin with the vector zero as starting point
    x=zeros(n)
    #The starting gradient
    g=A*x-b
    #The starting descent direction
    d=-g
    #iterations
    it=0
    #starting the residuals
    res=[norm(b-A*x)]
    # we begin the while loop
    while it<maxit && norm(g)>ϵ
        #We set everything as the CG method
        α=(norm(g)^2)/(transpose(d)*A*d)[1]
        x+=α*d
        β=(norm(g+α*A*d)^2)/(norm(g)^2)
        g=g+α*A*d
        d=-g+β*d
        #Append 
        push!(res,norm(b-A*x))
        it+=1
    end
    #We return the outputs
    Any[x,it,res]
end

CG (generic function with 1 method)

Lets use the Hilbert matrix of $n\times n$ as Benchmark, whose entries are $A_{i j}=1/(i+j-1)$, defined as a fucntion with input the dimension $n$. Lets do it using types to be faster.

In [23]:
#Define a constructor    
function Hilbert(n)
    #Define a zero matrix to fill it with the values
    H=zeros(n,n)
    for i in 1:n
        for j in 1:n
            H[i,j]=1/(i+j-1)
        end
    end
    H
end

Hilbert (generic function with 1 method)

We are going to use as parameters of error and maximum number of iterations the following

In [30]:
ϵ=1e-5
maxit=10000

10000

First lets try with n=5

In [31]:
n=5
A=Hilbert(n);
# b vector with ones
b=ones(n);

In [32]:
CG_result=CG(A,b,ϵ,maxit)

3-element Array{Any,1}:
  [5.000000212074378,-120.00000009629245,629.9999998500948,-1120.000000156727,629.9999998475234]                                                
 6                                                                                                                                              
  [2.23606797749979,0.9522398243032083,0.24206770158538768,0.042466353254903895,0.004676210060950159,0.0009940578846803702,7.358907261688369e-8]

We can see that the number of iterations required are

In [33]:
CG_result[2]

6

Now lets do with n=8

In [34]:
n=8
A=Hilbert(n);
# b vector with ones
b=ones(n);

In [35]:
CG_result=CG(A,b,ϵ,maxit)

3-element Array{Any,1}:
   [-7.9999849428891245,503.99978696527705,-7559.999320334311,46200.000864360256,-138600.00665425183,216216.00958881562,-168168.0046520919,51480.000369925896]                                                                                                                                                                                                                                                 
 18                                                                                                                                                                                                                                                                                                                                                                                                            
   [2.8284271247461903,1.3353352625460104,0.42688557603051086,0.10674953804216018,0.02158790633397045,0.003480324765524433,1.7891898825537587,0.0009251903373990505,0.0004810971

Now the number of iterations increased to 

In [36]:
CG_result[2]

18

Now with n=12

In [37]:
n=12
A=Hilbert(n);
# b vector with ones
b=ones(n);

In [38]:
CG_result=CG(A,b,ϵ,maxit)

3-element Array{Any,1}:
   [8.484573591086065,-533.6134714785092,7822.052041496177,-44196.88170190329,106571.39264773895,-79267.14812470903,-71538.38693044212,67140.91217765342,100705.88289639771,-27808.745219665838,-142932.18868474703,84125.13100674374]                                                                                                                                                                                     
 19                                                                                                                                                                                                                                                                                                                                                                                                                        
   [3.4641016151377544,1.7409647264705157,0.6424182675783826,0.19396136930963218,0.05060821290824378,0.011495533210329154,0.01956758723540717,0.00228888

Now the number of iterations increased a bit to 

In [40]:
CG_result[2]

19

Finally lets do it with n=20

In [41]:
n=20
A=Hilbert(n);
# b vector with ones
b=ones(n);

In [42]:
CG_result=CG(A,b,ϵ,maxit)

3-element Array{Any,1}:
   [9.984726814645823,-752.118463355912,13297.873788751594,-91781.03134761505,279561.6258098494,-315729.57084853284,-98111.3655344086,256123.04929580685,228920.60564174035,-52847.4036703173,-271362.839401672,-254180.40334148303,-38699.02807323009,212265.89890953858,327107.99221216806,216087.11450400276,-79577.276272531,-375194.8101861177,-355213.1489882011,400252.56558761734]
 37                                                                                                                                                                                                                                                                                                                                                                                       
   [4.47214,2.37603,1.00895,0.360153,0.115956,0.0340387,0.00917471,0.27289,0.0172364,0.00229508  …  0.0216188,0.0374905,0.0440745,0.00903355,0.0042782,0.00017474,0.000922782,5.33059e-5,1.47661e-5,5.032e-6]             

The final number of iterations is

In [43]:
CG_result[2]

37